-- ══════════════════════════════════════════════════════════════════════════════
-- EDEN CRUST PIZZA — SUPABASE POSTGRESQL SCHEMA & MENU DATA
-- Copy and paste this entire script into Supabase SQL Editor (https://supabase.com)
-- ══════════════════════════════════════════════════════════════════════════════

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. MENU CATEGORIES
CREATE TABLE IF NOT EXISTS public.menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. MENU ITEMS
CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  cat TEXT,
  price NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  desc_text TEXT DEFAULT '',
  img TEXT DEFAULT '',
  available BOOLEAN DEFAULT TRUE,
  variants JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. DEALS (COMBOS)
CREATE TABLE IF NOT EXISTS public.deals (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  price NUMERIC DEFAULT 0,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLES
CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT PRIMARY KEY,
  status TEXT DEFAULT 'available',
  persons INT DEFAULT 0,
  seats INT DEFAULT 4,
  reserved_for TEXT DEFAULT '',
  reserved_time TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  table_id BIGINT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'pending',
  note TEXT DEFAULT '',
  time TEXT,
  waiter TEXT,
  is_add_on BOOLEAN DEFAULT FALSE,
  total NUMERIC DEFAULT 0,
  order_type TEXT DEFAULT 'Dine-in',
  customer_phone TEXT DEFAULT '',
  customer_address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. UNPAID BILLS
CREATE TABLE IF NOT EXISTS public.unpaid_bills (
  bill_key TEXT PRIMARY KEY,
  order_id TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  time TEXT,
  add_on_tickets INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. INVENTORY
CREATE TABLE IF NOT EXISTS public.inventory (
  id BIGINT PRIMARY KEY,
  item TEXT NOT NULL,
  unit TEXT,
  stock NUMERIC DEFAULT 0,
  min NUMERIC DEFAULT 0,
  price NUMERIC DEFAULT 0,
  last TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. EMPLOYEES
CREATE TABLE IF NOT EXISTS public.employees (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  cnic TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  designation TEXT DEFAULT '',
  salary NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Present',
  address TEXT DEFAULT '',
  salary_payments JSONB NOT NULL DEFAULT '[]'::jsonb,
  advances JSONB NOT NULL DEFAULT '[]'::jsonb,
  attendance_log JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. PETTY CASH
CREATE TABLE IF NOT EXISTS public.petty_cash (
  id BIGINT PRIMARY KEY,
  name TEXT,
  category TEXT,
  amount NUMERIC DEFAULT 0,
  date TEXT,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. SALES LEDGER
CREATE TABLE IF NOT EXISTS public.sales_ledger (
  id TEXT PRIMARY KEY,
  date TEXT,
  table_id BIGINT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total NUMERIC DEFAULT 0,
  payment TEXT,
  waiter TEXT,
  discount NUMERIC DEFAULT 0,
  per_head NUMERIC DEFAULT 0,
  order_type TEXT DEFAULT 'Dine-in',
  customer_phone TEXT DEFAULT '',
  customer_address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. EXPENSE LEDGER
CREATE TABLE IF NOT EXISTS public.expense_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT,
  category TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT DEFAULT '',
  meta JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unpaid_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.petty_cash ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public all menu_categories" ON public.menu_categories;
CREATE POLICY "Allow public all menu_categories" ON public.menu_categories FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all menu_items" ON public.menu_items;
CREATE POLICY "Allow public all menu_items" ON public.menu_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all deals" ON public.deals;
CREATE POLICY "Allow public all deals" ON public.deals FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all tables" ON public.tables;
CREATE POLICY "Allow public all tables" ON public.tables FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all orders" ON public.orders;
CREATE POLICY "Allow public all orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all unpaid_bills" ON public.unpaid_bills;
CREATE POLICY "Allow public all unpaid_bills" ON public.unpaid_bills FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all inventory" ON public.inventory;
CREATE POLICY "Allow public all inventory" ON public.inventory FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all employees" ON public.employees;
CREATE POLICY "Allow public all employees" ON public.employees FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all petty_cash" ON public.petty_cash;
CREATE POLICY "Allow public all petty_cash" ON public.petty_cash FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all sales_ledger" ON public.sales_ledger;
CREATE POLICY "Allow public all sales_ledger" ON public.sales_ledger FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all expense_ledger" ON public.expense_ledger;
CREATE POLICY "Allow public all expense_ledger" ON public.expense_ledger FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public all settings" ON public.settings;
CREATE POLICY "Allow public all settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

-- REALTIME REPLICATION (SAFE ADD)
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.unpaid_bills;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.tables;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- ══════════════════════════════════════════════════════════════════════════════
-- SEED EDEN CRUST PIZZA FULL MENU DATA
-- ══════════════════════════════════════════════════════════════════════════════

INSERT INTO public.menu_categories (name) VALUES
  ('Eden Special Pizzas'),
  ('Eden Loaded Pizza'),
  ('Crust Pizza'),
  ('Eden''s Traditional Stuff Pizza'),
  ('Burgers'),
  ('Wraps'),
  ('Wings'),
  ('Fries'),
  ('Pasta'),
  ('Injected Broast Chicken'),
  ('Water & Cold Drinks'),
  ('Sauces & Extras')
ON CONFLICT (name) DO NOTHING;

-- INSERT MENU ITEMS
INSERT INTO public.menu_items (id, name, cat, price, discount, desc_text, img, available, variants) VALUES
  (1, 'Eden''s Special Pizza', 'Eden Special Pizzas', 650, 0, 'Special sauce, loaded chicken, veggies & extra mozzarella cheese', '🍕', true, '[{"label":"Small","price":650},{"label":"Medium","price":1200},{"label":"Large","price":1500},{"label":"Family","price":2400}]'::jsonb),
  (2, 'Pepperoni Special Pizza', 'Eden Special Pizzas', 1200, 0, 'Italian red sauce, extra mozzarella cheese & premium pepperoni slices', '🍕', true, '[{"label":"Medium","price":1200},{"label":"Large","price":1500},{"label":"Family","price":2400}]'::jsonb),
  (3, 'Deep Dish Special Pizza', 'Eden Special Pizzas', 1800, 0, 'Deep dish style layered with cheese, chicken tikka & special herbs', '🍕', true, '[{"label":"Medium","price":1800},{"label":"Large","price":2400}]'::jsonb),
  (4, 'Prestigious Special Pizza', 'Eden Special Pizzas', 700, 0, 'Chef signature sauce, smoked chicken, mushrooms, olives & sausages', '🍕', true, '[{"label":"Small","price":700},{"label":"Medium","price":1400},{"label":"Large","price":2000},{"label":"Family","price":2350}]'::jsonb),
  (5, 'Peri-Peri Pizza', 'Eden Loaded Pizza', 700, 0, 'Loaded, filled crust edge with spicy Peri-Peri chicken & jalapenos', '🍕', true, '[{"label":"Small","price":700},{"label":"Medium","price":1250},{"label":"Large","price":1750},{"label":"Family","price":2350}]'::jsonb),
  (6, 'Chicken BBQ Pizza', 'Eden Loaded Pizza', 600, 0, 'Smokey BBQ sauce, grilled chicken, onions & mozzarella cheese', '🍕', true, '[{"label":"Small","price":600},{"label":"Medium","price":1150},{"label":"Large","price":1400},{"label":"Family","price":2200}]'::jsonb),
  (7, 'Chicken Fajita Pizza', 'Eden Loaded Pizza', 500, 0, 'Fajita seasoned chicken, capsicum, onions & rich cheese', '🍕', true, '[{"label":"Small","price":500},{"label":"Medium","price":1050},{"label":"Large","price":1350},{"label":"Family","price":2000}]'::jsonb),
  (8, 'Chicken Tikka Pizza', 'Eden Loaded Pizza', 500, 0, 'Traditional tikka chicken, onions & mozzarella cheese', '🍕', true, '[{"label":"Small","price":500},{"label":"Medium","price":1050},{"label":"Large","price":1350},{"label":"Family","price":2000}]'::jsonb),
  (9, 'Chicken Supreme Pizza', 'Eden Loaded Pizza', 600, 0, 'Supreme mix of tikka & fajita chicken, olives, mushrooms & cheese', '🍕', true, '[{"label":"Small","price":600},{"label":"Medium","price":1150},{"label":"Large","price":1400},{"label":"Family","price":2200}]'::jsonb),
  (10, 'Mughlai Pizza', 'Eden Loaded Pizza', 600, 0, 'Rich Mughlai style chicken with aromatic spices & extra cheese', '🍕', true, '[{"label":"Small","price":600},{"label":"Medium","price":1150},{"label":"Large","price":1400},{"label":"Family","price":2200}]'::jsonb),
  (11, 'Crown Crust Pizza', 'Crust Pizza', 650, 0, 'Golden crown stuffed crust pockets filled with chicken & cheese', '🍕', true, '[{"label":"Small","price":650},{"label":"Medium","price":1200},{"label":"Large","price":1500},{"label":"Family","price":2400}]'::jsonb),
  (12, 'Kabab Crust Pizza', 'Crust Pizza', 650, 0, 'Crust ring stuffed with juicy seekh kebab slices & mozzarella', '🍕', true, '[{"label":"Small","price":650},{"label":"Medium","price":1150},{"label":"Large","price":1450},{"label":"Family","price":2350}]'::jsonb),
  (13, 'Royal Kabab Crust Pizza', 'Crust Pizza', 1400, 0, 'Royal style stuffed kebab crust topped with special sauces', '🍕', true, '[{"label":"Medium","price":1400},{"label":"Large","price":1850},{"label":"Family","price":2550}]'::jsonb),
  (14, 'Chicken Tandoori Pizza', 'Eden''s Traditional Stuff Pizza', 500, 0, 'Tandoori marinated chicken boti, onions & mozzarella', '🍕', true, '[{"label":"Small","price":500},{"label":"Medium","price":1050},{"label":"Large","price":1350},{"label":"Family","price":2000}]'::jsonb),
  (15, 'Bihari Kebab Pizza', 'Eden''s Traditional Stuff Pizza', 600, 0, 'Spicy Bihari kebab chunks, onions & mozzarella cheese', '🍕', true, '[{"label":"Small","price":600},{"label":"Medium","price":1250},{"label":"Large","price":1600},{"label":"Family","price":2350}]'::jsonb),
  (16, 'Malai Pizza', 'Eden''s Traditional Stuff Pizza', 650, 0, 'Creamy malai boti chicken, capsicum & cheese melt', '🍕', true, '[{"label":"Small","price":650},{"label":"Medium","price":1250},{"label":"Large","price":1600},{"label":"Family","price":2350}]'::jsonb),
  (17, 'Veg Lover Pizza', 'Eden''s Traditional Stuff Pizza', 500, 0, 'Fresh capsicum, onions, mushrooms, olives & sweet corn', '🍕', true, '[{"label":"Small","price":500},{"label":"Medium","price":1050},{"label":"Large","price":1350},{"label":"Family","price":2000}]'::jsonb),
  (18, 'Bonfire Pizza', 'Eden''s Traditional Stuff Pizza', 600, 0, 'Hot bonfire sauce, fajita chicken, jalapenos & tomatoes', '🍕', true, '[{"label":"Small","price":600},{"label":"Medium","price":1150},{"label":"Large","price":1450},{"label":"Family","price":2150}]'::jsonb),
  (19, 'Chicken Achari Pizza', 'Eden''s Traditional Stuff Pizza', 500, 0, 'Pickled achari chicken flavor with capsicum & olives', '🍕', true, '[{"label":"Small","price":500},{"label":"Medium","price":1050},{"label":"Large","price":1350},{"label":"Family","price":2000}]'::jsonb),
  (20, 'Zinger Burger', 'Burgers', 350, 0, 'Crispy zinger fillet with secret sauce & fresh lettuce', '🍔', true, '[]'::jsonb),
  (21, 'Special Burger', 'Burgers', 400, 0, 'Eden special loaded chicken patty burger', '🍔', true, '[]'::jsonb),
  (22, 'Chicken Patty Burger', 'Burgers', 300, 0, 'Juicy chicken patty with creamy mayo sauce', '🍔', true, '[]'::jsonb),
  (23, 'Double Burger', 'Burgers', 600, 0, 'Double patty & double cheese melt burger', '🍔', true, '[]'::jsonb),
  (24, 'BBQ Grilled Patty Burger', 'Burgers', 500, 0, 'Smokey grilled patty with BBQ sauce', '🍔', true, '[]'::jsonb),
  (25, 'Fillet Burger', 'Burgers', 550, 0, 'Tender chicken fillet burger with salad', '🍔', true, '[]'::jsonb),
  (26, 'Afghani Burger', 'Burgers', 450, 0, 'Traditional Afghani style spicy burger', '🍔', true, '[]'::jsonb),
  (27, 'Grill Burger', 'Burgers', 550, 0, 'Flame grilled chicken burger', '🍔', true, '[]'::jsonb),
  (28, 'Cadem Grill Burger', 'Burgers', 600, 0, 'Special Cadem style grilled burger', '🍔', true, '[]'::jsonb),
  (29, 'Turkish Wrap', 'Wraps', 450, 0, 'Turkish spiced chicken wrap with fresh salad', '🌯', true, '[]'::jsonb),
  (30, 'Eden Special Wrap', 'Wraps', 650, 0, 'Eden special loaded wrap with sauce', '🌯', true, '[]'::jsonb),
  (31, 'Arabic Wrap', 'Wraps', 550, 0, 'Arabic style chicken wrap with garlic mayo', '🌯', true, '[]'::jsonb),
  (32, 'Zinger Wrap', 'Wraps', 400, 0, 'Crispy zinger strips wrapped in paratha/tortilla', '🌯', true, '[]'::jsonb),
  (33, 'Fillet Wrap', 'Wraps', 600, 0, 'Grilled fillet strips wrap with special sauce', '🌯', true, '[]'::jsonb),
  (34, 'Peri-Peri Wings', 'Wings', 350, 0, 'Spicy oven baked Peri-Peri wings', '🍗', true, '[{"label":"5pc","price":350},{"label":"10pc","price":650}]'::jsonb),
  (35, 'BBQ Wings', 'Wings', 350, 0, 'Smokey BBQ glazed oven baked wings', '🍗', true, '[{"label":"5pc","price":350},{"label":"10pc","price":650}]'::jsonb),
  (36, 'Grilled Wings', 'Wings', 350, 0, 'Flame grilled seasoned wings', '🍗', true, '[{"label":"5pc","price":350},{"label":"10pc","price":650}]'::jsonb),
  (37, 'Crispy Wings', 'Wings', 350, 0, 'Golden crispy fried wings', '🍗', true, '[{"label":"5pc","price":350},{"label":"10pc","price":650}]'::jsonb),
  (38, 'French Fries', 'Fries', 200, 0, 'Crispy golden french fries', '🍟', true, '[]'::jsonb),
  (39, 'Regular Fries', 'Fries', 200, 0, 'Regular salted fries', '🍟', true, '[]'::jsonb),
  (40, 'Medium Fries', 'Fries', 300, 0, 'Medium size seasoned fries', '🍟', true, '[]'::jsonb),
  (41, 'Family Fries', 'Fries', 300, 0, 'Large jumbo family portion fries', '🍟', true, '[]'::jsonb),
  (42, 'Loaded Fries', 'Fries', 400, 0, 'Fries loaded with chicken chunks, cheese & sauces', '🍟', true, '[]'::jsonb),
  (43, 'Cheese Fries', 'Fries', 450, 0, 'Fries topped with hot melted cheese sauce', '🍟', true, '[]'::jsonb),
  (44, 'Creamy Pasta', 'Pasta', 400, 0, 'Rich creamy white alfredo sauce pasta', '🍝', true, '[{"label":"Half","price":400},{"label":"Full","price":800}]'::jsonb),
  (45, 'Special Pasta', 'Pasta', 500, 0, 'Eden special loaded cheese pasta', '🍝', true, '[{"label":"Half","price":500},{"label":"Full","price":1000}]'::jsonb),
  (46, 'Flaming Pasta', 'Pasta', 400, 0, 'Spicy red flaming sauce pasta', '🍝', true, '[{"label":"Half","price":400},{"label":"Full","price":800}]'::jsonb),
  (47, 'Crunchy Pasta', 'Pasta', 400, 0, 'Pasta topped with crispy chicken crunch', '🍝', true, '[{"label":"Half","price":400},{"label":"Full","price":800}]'::jsonb),
  (48, 'Injected Broast Chicken (Quarter)', 'Injected Broast Chicken', 600, 0, 'Juicy tender injected roast chicken - Quarter portion', '🍗', true, '[]'::jsonb),
  (49, 'Injected Broast Chicken (Half)', 'Injected Broast Chicken', 900, 0, 'Juicy tender injected roast chicken - Half portion', '🍗', true, '[]'::jsonb),
  (50, 'Injected Broast Chicken (Full)', 'Injected Broast Chicken', 1750, 0, 'Juicy tender injected roast chicken - Full portion', '🍗', true, '[]'::jsonb),
  (51, 'Small Water', 'Water & Cold Drinks', 50, 0, '500ml Mineral Water', '💧', true, '[]'::jsonb),
  (52, 'Large Water', 'Water & Cold Drinks', 100, 0, '1.5L Mineral Water', '💧', true, '[]'::jsonb),
  (53, 'Drink (350ml)', 'Water & Cold Drinks', 80, 0, '350ml Chilled Beverage Bottle/Can', '🥤', true, '[]'::jsonb),
  (54, 'Drink (1 Liter)', 'Water & Cold Drinks', 170, 0, '1 Liter Bottle', '🥤', true, '[]'::jsonb),
  (55, 'Drink (1.5 Liter)', 'Water & Cold Drinks', 200, 0, '1.5 Liter Bottle', '🥤', true, '[]'::jsonb),
  (56, 'Drink (2.25 Liter)', 'Water & Cold Drinks', 280, 0, '2.25 Liter Bottle', '🥤', true, '[]'::jsonb),
  (57, 'Dip Sauce', 'Sauces & Extras', 50, 0, 'Signature dip sauce', '🥣', true, '[]'::jsonb),
  (58, 'Mayo', 'Sauces & Extras', 50, 0, 'Garlic mayo sauce', '🥣', true, '[]'::jsonb),
  (59, 'Peri-Peri Sauce', 'Sauces & Extras', 50, 0, 'Spicy peri-peri dip sauce', '🥣', true, '[]'::jsonb),
  (60, 'Extra Chicken Topping', 'Sauces & Extras', 200, 0, 'Extra chicken topping for pizza/burger', '🥣', true, '[]'::jsonb),
  (61, 'Extra Cheese', 'Sauces & Extras', 200, 0, 'Extra melted mozzarella cheese topping', '🥣', true, '[]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, cat = EXCLUDED.cat, price = EXCLUDED.price,
  desc_text = EXCLUDED.desc_text, img = EXCLUDED.img, available = EXCLUDED.available,
  variants = EXCLUDED.variants;

-- INSERT DEALS
INSERT INTO public.deals (id, name, category, price, available, items) VALUES
  (1, 'Deal 1', 'Midnight Deals', 1420, true, '["1 Large Pizza (Fajita + Tikka only)", "1L Drink"]'::jsonb),
  (2, 'Deal 2', 'Midnight Deals', 1250, true, '["1 Medium Eden''s Special Pizza", "1x 350ml Drink"]'::jsonb),
  (3, 'Deal 3', 'Midnight Deals', 2700, true, '["2 Large Pizzas (Fajita + Tikka)", "1.5L Drink"]'::jsonb),
  (4, 'Deal 4', 'Midnight Deals', 1120, true, '["2 Small Pizzas (Fajita + Tikka)", "2x 350ml Drink"]'::jsonb),
  (5, 'Deal 5', 'Midnight Deals', 2120, true, '["2 Medium Pizzas (Fajita + Tikka)", "1L Drink"]'::jsonb),
  (6, 'Deal 6', 'Midnight Deals', 4000, true, '["3 Large Pizzas (Fajita + Tikka)", "1.5L Drink"]'::jsonb),
  (7, 'Deal 7', 'Midnight Deals', 2400, true, '["1 Large Pizza", "1 Zinger Burger", "1.5L Drink", "1 Large Fries"]'::jsonb),
  (8, 'Deal 8', 'Midnight Deals', 2100, true, '["1 Large Pizza", "1 Zinger Burger", "5 Wings", "1.5L Drink"]'::jsonb),
  (9, 'Eden''s Special Deal', 'Midnight Deals', 1650, true, '["1 Large Pizza (all 5 loaded flavors)", "1.5L Drink"]'::jsonb),
  (10, 'Deal 10 — Birthday Deal', 'Midnight Deals', 6450, true, '["2 Large Pizzas", "10 Wings", "6 Zinger Burgers", "Family Fries", "1.5L Drink", "1 Cake"]'::jsonb),
  (11, 'Deal 11', 'Midnight Deals', 570, true, '["1 Zinger Burger", "Regular Fries", "1x 350ml Drink"]'::jsonb),
  (12, 'Deal 12', 'Midnight Deals', 950, true, '["2 Zinger Burgers", "Regular Fries", "2x 350ml Drink"]'::jsonb),
  (13, 'Deal 13', 'Midnight Deals', 620, true, '["1 Zinger Burger", "5pc Wings", "1x 350ml Drink"]'::jsonb),
  (14, 'Deal 14', 'Midnight Deals', 1500, true, '["4 Zinger Burgers", "1x 350ml Drink"]'::jsonb),
  (15, 'Deal 15', 'Midnight Deals', 2150, true, '["5 Zinger Burgers", "1 Large Fries", "1.5L Drink"]'::jsonb),
  (16, 'Deal 16', 'Midnight Deals', 1050, true, '["1 Chicken Broast Roll", "1 Drink"]'::jsonb),
  (17, 'Deal 17', 'Midnight Deals', 550, true, '["1 Special Pasta (Small)", "1x 350ml Drink"]'::jsonb),
  (18, 'Deal 18', 'Midnight Deals', 700, true, '["5 Crispy Wings", "5 Nuggets", "2x 350ml Drink"]'::jsonb),
  (19, 'Deal 19', 'Midnight Deals', 430, true, '["1 Turkish Wrap", "1x 350ml Drink"]'::jsonb),
  (20, 'Deal 20', 'Midnight Deals', 630, true, '["10 Hot Shots", "Regular Fries", "1x 350ml Drink"]'::jsonb),
  (21, 'Deal 21', 'Midnight Deals', 420, true, '["1 Loaded Fries (Small)", "1x 350ml Drink"]'::jsonb),
  (22, 'Deal 22', 'Midnight Deals', 380, true, '["5 Grilled Wings", "1x 350ml Drink"]'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, category = EXCLUDED.category, price = EXCLUDED.price,
  available = EXCLUDED.available, items = EXCLUDED.items;

