-- ══════════════════════════════════════════════════════════════════════════════
-- EDEN CRUST PIZZA — SUPABASE POSTGRESQL SCHEMA & MENU DATA
-- Copy and paste this entire script into Supabase SQL Editor (https://supabase.com)
-- ══════════════════════════════════════════════════════════════════════════════

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. MENU CATEGORIES
CREATE TABLE IF NOT EXISTS public.menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. MENU ITEMS
CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  cat TEXT,
  price NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  desc_text TEXT DEFAULT '',
  img TEXT DEFAULT '',
  available BOOLEAN DEFAULT TRUE,
  variants JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. DEALS (COMBOS)
CREATE TABLE IF NOT EXISTS public.deals (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  price NUMERIC DEFAULT 0,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABLES
CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT PRIMARY KEY,
  status TEXT DEFAULT 'available',
  persons INT DEFAULT 0,
  seats INT DEFAULT 4,
  reserved_for TEXT DEFAULT '',
  reserved_time TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  table_id BIGINT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'pending',
  note TEXT DEFAULT '',
  time TEXT,
  waiter TEXT,
  is_add_on BOOLEAN DEFAULT FALSE,
  total NUMERIC DEFAULT 0,
  order_type TEXT DEFAULT 'Dine-in',
  customer_phone TEXT DEFAULT '',
  customer_address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. UNPAID BILLS
CREATE TABLE IF NOT EXISTS public.unpaid_bills (
  bill_key TEXT PRIMARY KEY,
  order_id TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  time TEXT,
  add_on_tickets INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. INVENTORY
CREATE TABLE IF NOT EXISTS public.inventory (
  id BIGINT PRIMARY KEY,
  item TEXT NOT NULL,
  unit TEXT,
  stock NUMERIC DEFAULT 0,
  min NUMERIC DEFAULT 0,
  price NUMERIC DEFAULT 0,
  last TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. EMPLOYEES
CREATE TABLE IF NOT EXISTS public.employees (
  id BIGINT PRIMARY KEY,
  name TEXT NOT NULL,
  cnic TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  designation TEXT DEFAULT '',
  salary NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Present',
  address TEXT DEFAULT '',
  salary_payments JSONB NOT NULL DEFAULT '[]'::jsonb,
  advances JSONB NOT NULL DEFAULT '[]'::jsonb,
  attendance_log JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. PETTY CASH
CREATE TABLE IF NOT EXISTS public.petty_cash (
  id BIGINT PRIMARY KEY,
  name TEXT,
  category TEXT,
  amount NUMERIC DEFAULT 0,
  date TEXT,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. SALES LEDGER
CREATE TABLE IF NOT EXISTS public.sales_ledger (
  id TEXT PRIMARY KEY,
  date TEXT,
  table_id BIGINT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total NUMERIC DEFAULT 0,
  payment TEXT,
  waiter TEXT,
  discount NUMERIC DEFAULT 0,
  per_head NUMERIC DEFAULT 0,
  order_type TEXT DEFAULT 'Dine-in',
  customer_phone TEXT DEFAULT '',
  customer_address TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. EXPENSE LEDGER
CREATE TABLE IF NOT EXISTS public.expense_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT,
  category TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT DEFAULT '',
  meta JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unpaid_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.petty_cash ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all menu_categories" ON public.menu_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all menu_items" ON public.menu_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all deals" ON public.deals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all tables" ON public.tables FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all unpaid_bills" ON public.unpaid_bills FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all inventory" ON public.inventory FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all employees" ON public.employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all petty_cash" ON public.petty_cash FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all sales_ledger" ON public.sales_ledger FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all expense_ledger" ON public.expense_ledger FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

-- REALTIME REPLICATION
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.unpaid_bills;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tables;

-- ══════════════════════════════════════════════════════════════════════════════
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, category = EXCLUDED.category, price = EXCLUDED.price,
  available = EXCLUDED.available, items = EXCLUDED.items;
